### ISSUE TITLE
Xdebug Toggler

### ISSUE THREAD

**Issue by benmatselby** [mac-cain13/xdebug-helper-for-safari#9]
Hi there,

I've installed your plugin as I wanted to see how it differed from [Xdebug Toggler](http://www.soulbroken.co.uk/code/xdebugtoggler/) which has been around for a couple of years. There doesn't seem to be a whole lot of difference apart from the extra options to profile and trace which is a great addition

Is there a reason why you didn't try to extend Xdebug Toggler, as we now have two extensions on the market. It feels like we could have worked together on this one. It looks like since Safari 6 you can do a little more nice UI features which were not available when I was creating this.

Nice work on the extension.

**Comment by mac-cain13** [comment]
Hi Ben!

Thanks for contacting me. Great that you've found this extension and did install/play with it.

I've seen, and even used, your Xdebug Toggler extension. It's a nice extension, compliments on creating it! There are indeed not to much differences between the two extension apart from the profile and trace options.

There are two reasons I started my own extension instead of contributing to yours:
1. I had already developed [Xdebug Helper for Chrome](https://github.com/wrep/xdebug-helper-for-chrome) a few years back, but I've switched to Safari as my default browser for quite some time now and I wanted to learn some more about creating a Safari extension.
2. I didn't realize your extensions was on Github until after I started developing my own extension.

Please feel free to contribute to this extension and/or take code from this extension to improve Xdebug Toggler if you like to.

Hope this makes things somewhat more clear!

Cheers and keep up the nice work! (Also like the Sublime plugins you made, I will give them a try soon!)
